dubbo:
  application:
    name: class-service
  registry:
    address: zookeeper://134.175.98.171:2181
  protocol:
    #自动查找一个可用的端口，默认是20880
    port: -1
  consumer:
    #首次启动不检查提供者是否存在
    check: false
spring:
  datasource:
    url: jdbc:mysql:///db_class?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

