dubbo:
  application:
    name: stu-service
  registry:
    address: zookeeper://134.175.98.171:2181
  protocol:

    port: -1
  consumer:

    check: false
spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver